### ISSUE TITLE
Addons that are not addUserStatuses do not run in Edge

### ISSUE THREAD

**Issue by mybearworld** [imadeanaccount1/wasteof.plus#13]
profileHoverCards, and even just the simple
```
console.log("Hello, world");
```
addon do not run

**Comment by mybearworld** [comment]
This makes it impossible for me to use this or test addons lol

**Comment by mybearworld** [comment]
ok that's weird, even just the simple
```
console.log("Hello, world");
```
addon does not run

**Comment by imadeanaccount1** [comment]
huh, i wonder why...

**Comment by imadeanaccount1** [comment]
@mybearworld i am actively investigating this!

**Comment by imadeanaccount1** [comment]
@mybearworld I can't seem to reproduce the error you are talking about. Is it the same error as issue #14 (hovercard addon doesn't work when signed out wasteof), because I have just merged a PR to fix that one.

**Comment by mybearworld** [comment]
> Is it the same error as issue #14 (hovercard addon doesn't work when signed out wasteof), because I have just merged a PR to fix that one.

No, I am signed in.

> otherwise, can you share your fork so i can reproduce the issue. thanks!

What exactly do you mean? https://github.com/mybearworld/fork-wasteof.plus is my fork, but that's just the exact same as this repository.

**Comment by imadeanaccount1** [comment]
Is it up to date? Try pulling the latest changes from this repo

**Comment by imadeanaccount1** [comment]
Let me download that one and try again... btw, to test the latest version you need to rename either manifest_chromium or manifest_firefox to be manifest.json

**Comment by imadeanaccount1** [comment]
Oh yes! You have to add addons to enabled addons for them to work. Also, if you show the extension in toolbar (right click the extension under three dots > extensions) and use open the extension popup to enable your addon, it should work. Example:

![image](https://github.com/imadeanaccount1/wasteof.plus/assets/138229538/d9909514-0df9-4cf8-9af0-e19b3ce6251b)

**Comment by mybearworld** [comment]
enabledAddons being `defaultEnabledAddons`? Clicking on the extension pop up doesn't do anything.

**Comment by imadeanaccount1** [comment]
@mybearworld if you want your addon to be enabled by default, it must be added to defaultEnabledAddons in the background script.

**Comment by imadeanaccount1** [comment]
@mybearworld is the extension pinned to the toolbar?

**Comment by imadeanaccount1** [comment]
@mybearworld If you click the browser three dots menu > Extensions > the three dots next to wasteof.plus > Show on toolbar

**Comment by mybearworld** [comment]
It is!
![it being pinned](https://github.com/imadeanaccount1/wasteof.plus/assets/130385691/9275d9b8-48d3-4d47-8c00-6888d0786cec)

**Comment by imadeanaccount1** [comment]
Can you try this version of the extension?
[wasteof.plus-signed-out-hovercard-bug.zip](https://github.com/imadeanaccount1/wasteof.plus/files/12062752/wasteof.plus-signed-out-hovercard-bug.zip)

**Comment by imadeanaccount1** [comment]
@mybearworld Also, are any errors being generated under the errors section? You can check under edge://extensions under the section that says errors:
<img width="554" alt="image" src="https://github.com/imadeanaccount1/wasteof.plus/assets/138229538/114d39c4-edfd-4d5f-80d2-d717614d5ad8">

The last thing I can think of would be that you haven't reloaded the extension after making changes. You have to click the "Reload" button shown in the image above to fetch the latest extension code.

**Comment by mybearworld** [comment]
With that zip file, it works, (ignoring that every single hovercard links to jeffalo lol)

**Comment by mybearworld** [comment]
With deleting my fork and readding it, it errors like this:
![**Errror** Manifest file is missing or unreadable](https://github.com/imadeanaccount1/wasteof.plus/assets/130385691/0378c2cc-a66c-432b-92e2-90ec9eb7cfd3)

**Comment by imadeanaccount1** [comment]
This is a good sign. You have to rename manifest_chromium.json to manifest.json.

**Comment by mybearworld** [comment]
That makes it work! (except that all hovercards link to jeffalo, but i'm pretty sure that's intentional)

**Comment by imadeanaccount1** [comment]
@mybearworld The plan is to have GitHub actions that generate Artifacts with these already pre-renamed so that I can create GitHub releases with the versions for firefox and chromium repectively. the reason for this is that firefox and chrome use different manifest formats. Also, you can run `npm run build:chrome` to auto-rename the manifest_chromium.json to manifest.json and `npm run build:firefox` to auto-rename the firefox manifest.

**Comment by mybearworld** [comment]
It might be better to copy the respective manifest file, and add manifest.json to a .gitignore file, so that testing forks would be easier.

**Comment by imadeanaccount1** [comment]
I'm so glad you fixed the issue! :D the jeffalo bug isn't actually intentional, though, there's probably an error in some console log. You should be able to develop addons now though!

**Comment by imadeanaccount1** [comment]
@mybearworld Yes, the plan is to gitignore manifest.json. Also, `npm run build:chrome/firefox` already copies it (to avoid losing the data when you use the alternate command).

**Comment by mybearworld** [comment]
I should probably open a separate issue on the jeffalo invasion

> @mybearworld Yes, the plan is to gitignore manifest.json. Also, `npm run build:chrome/firefox` already copies it (to avoid losing the data when you use the alternate command).

Ah, okay, I misunderstood this.

**Comment by imadeanaccount1** [comment]
yes, that should probably be a separate issue, as I cannot reproduce it atm. I will look into it further, though!
