### ISSUE TITLE
Hovercards all link to Jeffalo

### ISSUE THREAD

**Issue by mybearworld** [imadeanaccount1/wasteof.plus#16]
![A hovercard linking to Jeffalo on imadeanaccount](https://github.com/imadeanaccount1/wasteof.plus/assets/130385691/4d8b4ab8-f3ca-4e97-85b3-fdfddeae83b2)

Console error:

```
addon.js:47  Uncaught (in promise) ReferenceError: loggedinUser is not defined
    at fillInHoverCardTemplate (addon.js:47:36)
```

**Comment by imadeanaccount1** [comment]
Oh, I just fixed that issue. I will push the fix soon!

**Comment by imadeanaccount1** [comment]
@mybearworld Can you confirm whether this bug is fixed in the latest version? Thanks!

**Comment by mybearworld** [comment]
It's fixed!
