### ISSUE TITLE
Format the code

### ISSUE THREAD

**Issue by mybearworld** [imadeanaccount1/wasteof.plus#6]
It can be hard to read at times, this would make it easier.

**Comment by imadeanaccount1** [comment]
Yeah, I'm planning to do this for all of the addons after merging the current PR.

**Comment by mybearworld** [comment]
> I'm also planning on just cleaning it up a little more (getting rid of console logs, unnecessary comments, etc.) 👍

That's great! Maybe I'll able to actually try to make an addon then lol

**Comment by imadeanaccount1** [comment]
:D :D :D

**Comment by imadeanaccount1** [comment]
@mybearworld I just installed/setup ESLint so that formatting will be much better, will create a PR soon.
