### ISSUE TITLE
Polls not appearing

### ISSUE THREAD

**Issue by illogicalapple** [imadeanaccount1/wasteof.plus#73]
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/80916557/08d4a517-25b8-4b31-b99b-30bd68641f90)
I saw the poll once and then it disappeared (?)

**Comment by imadeanaccount1** [comment]
Oh, okay. This sounds like it's the same bug as #58, for which the fix is in active development in #66. With this bug, you will have to reload the page to get the polls to render again, but as I said, I am working on a fix and will let you know when it's patched!

**Comment by imadeanaccount1** [comment]
Duplicate of #58. (I'm closing this as further discussion will continue in #58)

**Comment by imadeanaccount1** [comment]
@all-contributors please add @illogicalapple for bug

**Comment by illogicalapple** [comment]
> @all-contributors please add @illogicalapple for bug

i feel so validated

**Comment by imadeanaccount1** [comment]
> i feel so validated

that's the point of all-contributors i guess :)
