### ISSUE TITLE
Idea: Large icons for extensions:

### ISSUE THREAD

**Issue by jakednolastname** [imadeanaccount1/wasteof.plus#83]
Pretty self-explanatory, I've made some mockup icons:

profileHoverCards
![cards](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/4150ccc1-0a6d-4660-831d-e1a8a41ac43e)

addMessageCountBadge
![notifbadge](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/d6a1db39-16fb-410b-8514-bfd1a7818fb8)

addMessageNotifications
![notifs](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/f2e891b4-de21-4aab-9c0d-c74f789196e7)

hashtags
![hashtags](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/9a8239b7-9d63-4ba1-9e86-f696d6168862)

polls
![polls](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/6e960339-2ec3-4526-8ea1-9127a0c736d5)

chatPresenceNotify
![chatpresence](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/dd86def9-cb93-4b1c-b918-fe5fe615cc63)

addUserStatuses
![badges](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/faa6274a-6b25-4b33-853f-935d253d476f)

**Comment by jakednolastname** [comment]
> Woah, these are very cool!! I think these would primarily be most useful to use these in the extension README and the wasteof.plus website. :)

Sounds good!

**Comment by imadeanaccount1** [comment]
Would you like to make one for the seen posts addon (#4) (Image shown below) and #37 (image also shown below)?
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/138229538/f18ee346-981b-4a04-8ff4-7abead309a0d)
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/138229538/c56c1b2e-bbfc-4c55-93f5-1bf7e949be43)

**Comment by jakednolastname** [comment]
Sure, give me a minute and i'll see what I can throw together.

**Comment by jakednolastname** [comment]
This one could be improved on when the addon comes out because I usually inspect element in what I want it to say and then screenshot that so it always looks right. 

![unread](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/08ffa917-f897-4e4a-b246-6727aeb579b0)

**Comment by jakednolastname** [comment]
will work on repost viewer addon icon next.

**Comment by jakednolastname** [comment]
For this one i just added most of the people I saw on the explore page.

![reposts](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/6e60498a-8834-43a8-8b78-2367ce0743b5)

**Comment by imadeanaccount1** [comment]
@all-contributors please add @jakednolastname for design

**Comment by imadeanaccount1** [comment]
@all-contributors please add @jakednolastname for code, ideas, design

**Comment by imadeanaccount1** [comment]
@all-contributors please add @jakednolastname for code, ideas, design

**Comment by jakednolastname** [comment]
@imadeanaccount1 just mention me here if you need more icons

**Comment by imadeanaccount1** [comment]
great! :D

**Comment by imadeanaccount1** [comment]
> @imadeanaccount1 just mention me here if you need more icons

Could you make some for Switch Accounts (#128), Custom Navigation (#117), and Auto-Love posts (#115)

**Comment by imadeanaccount1** [comment]
@jakednolastname bump (see my last comment)
